<?
$aMenuLinks = Array(
    Array(
        "О системе",
        "/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Тарифы",
        "/#tarifs",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Разработчикам",
        "/development/",
        Array(),
        Array(),
        ""
    ),
    Array(
        "Контакты",
        "/contacts/",
        Array(),
        Array(),
        ""
    ),
);
?>